name: Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: install git
        #run: |
        #  apt-get update
        #  apt-get install -y git
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: GOPROXY=direct go build -v ./...
      - name: Get ssh keys and set perm
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | openssl base64 -A -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy using RSYNC
        run: scp -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa hiveos-prometheus ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/hiveos-prometheus/hiveos-prometheus


